### ISSUE TITLE
Playback queue ended  Trigger  twice

### ISSUE THREAD

**Issue by mzyisbest** [DoubleSymmetry/react-native-track-player#1243]
**Describe the bug**
"Playback queue ended" monitoring is always called twice in a row, and each time it is the penultimate in my playback queue. It will be triggered after playing. Personally, I think it should be triggered after playing the last one

**To Reproduce**

**Environment (please complete the following information):**
react-native-track-player 2.0.3

**Code**
  TrackPlayer.addEventListener('playback-queue-ended', async () => {
    const queue = await TrackPlayer.getQueue();
    const id = await TrackPlayer.getCurrentTrack();
    console.log('******** remote-ended ********', id, queue);
    if (queue && queue.length - 1 == id) {
      await Player.next();
    }
  });

**Comment by hiroyaiizuka** [comment]
same problem +1

**Comment by dcvz** [comment]
It should definitely be triggered after playing the last item, this sounds like a bug.
Thanks for reporting @mzyisbest - we'll look into it!

**Comment by NguyenHoangNhatPhi** [comment]
You can use lodash/debounce to fix this one.

const handlePlaybackQueueEndedDebounce = debounce(function(){

// to do something

},500)

**Comment by bradleyflood** [comment]
Resolved but we can continue the conversation in #1349

**Comment by mmmoussa** [comment]
I am currently using v2.2.0-rc2 which includes this fix but I am still seeing the event get fired twice on iOS: once upon reaching the last track and once when the queue has actually ended. This is the exact same bug I was experiencing with v2.1.2 before I upgraded.
