### ISSUE TITLE
XCode 13 IOS build breaks because of React Native Track Player

### ISSUE THREAD

**Issue by NS-BOBBY-C** [DoubleSymmetry/react-native-track-player#1274]
**Describe the bug**
React Native Track Player in XCode 13 causes our IOS build to fail. I'm seeing reproducible results to [this thread](https://developer.apple.com/forums/thread/682351) and am able to change the react-native-track-player deployment target to make my build work again.

> Also had the same problem (xCode 13.0 beta 5 (13A5212g) ) only with types that are available from iOS13. Managed to workaround it by increasing the iOS deployment target to 13 of submodule, which in turn asked to increase the project iOS version, which gave a lot of warnings but no errors, so I was able to build my App and test it.
> 
> This works for me now, but definitely not a right solution, just a temporary. Lets hope for the fix in the next release.
>
> Posted 1 month ago by Randja

(change this from 10.0 to 13.0 and the app builds again)
<img width="651" alt="Screen Shot 2021-09-21 at 5 30 36 PM" src="https://user-images.githubusercontent.com/29097404/134251108-eb9abfb2-52dd-450d-b309-507e9b4c3e57.png">

**To Reproduce**
Run current project with release v2.0.1 with XCode 13 build. The project is proprietary, but I am willing to chat to help resolve the issue! Can be easily persuaded to help fix if its an easy fix :)

**Environment (please complete the following information):**
Run `react-native info` in your project and share the content.
```bash
System:
    OS: macOS 11.5.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 1.83 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.18.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 25, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3
      System Images: android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_272 - /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: ^5.0.1 => 5.0.1 
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
What `react-native-track-player` version are you using?
```bash
➜  mobile git:(development) ✗ yarn list react-native-track-player   
yarn list v1.22.10
warning ../package.json: No license field
warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ react-native-track-player@2.0.1
```
Are you testing on a real device or in the simulator? Which OS version are you running?
iPhone 11 Simulator (iOS 15.0)

**Code**
Installation correctly followed and deployed into our production environment. Has been working until today!

**Comment by jplandry908** [comment]
My project started failing as well after the upgrade.
![image](https://user-images.githubusercontent.com/14008273/134263350-44cbed95-6683-43bb-8bca-e437bf22590d.png)

**Comment by maxckelly** [comment]
Also experiencing the same issue after updating. @NS-BOBBY-C increasing to 13.0 makes it buildable.

**Comment by jplandry908** [comment]
I fixed this error by upgrading from v2.0.3 to 2.1.0, and then upgrading my pod file target to 11.0 (from 10.0). My project deployment target in XCode is currently still 10.0.

**Comment by andrewdazs** [comment]
I use track player v1.2.7 and changing the deployment target to 11.0 works for me, but when I close the project and open it again the deployment target returns to 10.0. What can I do in this case?

**Comment by Johkade** [comment]
^update: after downgrading Xcode to 12.5 (which i used before the upgrade to 13) my issue was resolved again. Of course this is only a temporary solution. 
This is where you can get older versions of xcode: https://developer.apple.com/download/all/ .
My steps were: uninstall xcode 13, download and unpack the xip-file for 12.5, then do a clean build.

**Comment by jplandry908** [comment]
HI @Johkade. I had to upgrade to v2.1.0 (was on v2.0.3) to get it to work. That upgrade was easy; however, I had to rewrite a bit of code when going from v1 to v2 (https://github.com/DoubleSymmetry/react-native-track-player#%EF%B8%8F-v2-migration-guide). Whenever you have time, it may be worth the effort to upgrade and then attempt Xcode 13 with v11.0 deployment targets.

**Comment by andrewdazs** [comment]
For those who are still having this problem, for me it was not necessary to upgrade to version v2. I just created a patch by changing ` s.platform` to `11` in the `react-native-track-player.podspec` file.

Like this: `s.platform = :ios, "11.0"`. After this it worked normally.

**Comment by dcvz** [comment]
Hi folks 👋 Support for Xcode 13 has landed in `v2.1.0` and it's recommended that you migrate to that version.

**Comment by therealkh** [comment]
> Hi folks 👋 Support for Xcode 13 has landed in `v2.1.0`. There's also been been other improvements and fixes for iOS 15 so we really recommend that you move to the latest `2.X.X` version.
> 
> I will close this issue as there has been a fix shipped.

I am still having this issue while building relea
<img width="1104" alt="Снимок экрана 2021-09-28 в 15 40 23" src="https://user-images.githubusercontent.com/65399389/135072262-486be894-b589-4ac1-a211-fcf48f4de9e8.png">
se

**Comment by JensDeTaey27** [comment]
I'm having the same issue on release builds as @therealkh

**Comment by dcvz** [comment]
Is one of you able to share your projects?

**Comment by josemojena** [comment]
> this

Changing platform support from 10.0 to 11.0 works but the audio player does not show on the screen when iPhone is lock or the app is minimized.

**Comment by jplandry908** [comment]
Hi @josemojena. I changed my app from v10 to v11 to get mine to work, but the audio player does still show when the iPhone is locked or minimized. I am currently on the latest version, v2.1.1.

**Comment by josemojena** [comment]
Yeah, the problem is with the old version, I'm using 1.2.7, and migrate the latest version at this moment is not the first option. Thanks!!!

**Comment by carldatu** [comment]
> > Hi folks 👋 Support for Xcode 13 has landed in `v2.1.0`. There's also been been other improvements and fixes for iOS 15 so we really recommend that you move to the latest `2.X.X` version.
> > I will close this issue as there has been a fix shipped.
> 
> I am still having this issue while building release
> 
> <img alt="Снимок экрана 2021-09-28 в 15 40 23" width="1104" src="https://user-images.githubusercontent.com/65399389/135072262-486be894-b589-4ac1-a211-fcf48f4de9e8.png">

Did you resolve issue ?

**Comment by carldatu** [comment]
Finally, I fixed this issue. To solve this issue, please do these step.
* upgrade react-native-track-player -> 2.1.0 over
* upgrade pod file -> platform :ios, '11.0'
* upgrade ios development target verion -> 11.0 
 Note: don't forget to upgrade ios development target version. It is very important.
