### ISSUE TITLE
Not working because of pod install not working due to SwiftAudioEx 0.14.5 is missing. 

### ISSUE THREAD

**Issue by jr00n** [DoubleSymmetry/react-native-track-player#1344]
**Describe the bug**
In my react-native project added this dependency:
"react-native-track-player": "^2.1.2"

**To Reproduce**
npx react-native init AwesomeProject
npm i react-native-track-player
npm install
cd ios
pod install

```
Auto-linking React Native module for target 'AwesomeProject': react-native-track-player
Analyzing dependencies
Downloading dependencies
Installing SwiftAudioEx (0.14.5)
Installing react-native-track-player (2.1.2)
Generating Pods project
Integrating client project
Pod installation complete! There are 54 dependencies from the Podfile and 46 total pods installed.

[!] Unable to read the license file 'LICENSE' for the spec 'SwiftAudioEx (0.14.5)'
[!] Unable to read the license file 'LICENSE' for the spec 'SwiftAudioEx (0.14.5)'
[!] Unable to read the license file 'LICENSE' for the spec 'SwiftAudioEx (0.14.5)'
[!] Unable to read the license file 'LICENSE' for the spec 'SwiftAudioEx (0.14.5)'
```

**Comment by mabatak1** [comment]
Finally, I fixed this issue. To solve this issue, please do these step.

upgrade react-native-track-player -> 2.1.0 over
upgrade pod file -> platform :ios, '11.0'
upgrade ios development target verion -> 11.0
Add this line to your Podfile in your ios folder: `pod 'React-Core', :path => '../node_modules/react-native/', :modular_headers => true`
Note: don't forget to upgrade ios development target version. It is very important.

**Comment by LorandP** [comment]
@mabatak1 I can confirm that this works on xCode 13.

**Comment by khanhtn91** [comment]
I have the same issue,

xCode 13.2 RC
react-native-track-player -> 2.1.2
IOS deployment target -> 11.0
pod file -> platform :ios, '11.0'
pod file -> pod 'React-Core', :path => '../node_modules/react-native/', :modular_headers => true
But not work for me :((((

**Comment by khanhtn91** [comment]
Hi Guy, 

The problem is [here](https://github.com/DoubleSymmetry/react-native-track-player/commit/cca3aaa3076db1e5d806eb00416748ede709352e)  ,
SwiftAudioEx v0.14.5 does not have a LICENSE file, a LICENSE added in v0.14.6

Fixed this issue

**Comment by zreaqqasem** [comment]
any update guys? I also facing this issue

**Comment by mattdwardle** [comment]
I upgraded to SwiftAudioEx v0.14.6 by manually updating the podspec for this package then the license message goes away. But everytime I build in Xcode I am still getting this error: `/Build/Products/Debug-iphoneos/SwiftAudioEx/SwiftAudioEx.modulemap' not found`

I have also tried removing all pods and reinstalling them again. I am. not sure what is going on I can see there is a pod installed for SwiftAudioEx.

I am also working on an M1 mac so not sure if that is related?

**Comment by waqas19921** [comment]
@mattdwardle Please check your XCode project target iOS version is same as defined in pod file,
I have similar issue
as stated here
https://stackoverflow.com/a/67867179/5257674

**Comment by bradleyflood** [comment]
Hi all and thanks. This should be resolved in updated version of RNTP. See here https://github.com/DoubleSymmetry/react-native-track-player/issues/1248#issuecomment-942025812

**Comment by wq13718048209** [comment]
react-native : "0.63.4"
react-native-track-player: "^2.1.2"
xcode:"13.2.1"

[!] Unable to find a specification for `SwiftAudioEx (= 0.14.5)` depended upon by `react-native-track-player`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

There is still this problem, isn't there a perfect solution, the project is not working right now

**Comment by wq13718048209** [comment]
> 大家好，谢谢。这应该在 RNTP 的更新版本中得到解决。见这里[#1248（评论）](https://github.com/DoubleSymmetry/react-native-track-player/issues/1248#issuecomment-942025812)

I don't think it worked
