### ISSUE TITLE
Play button not working after bringing app to foreground(iPhone 11, iOS 14.6)

### ISSUE THREAD

**Issue by janlonden** [doublesymmetry/react-native-track-player#1402]
**Describe the Bug**
When I pause a track, lock my screen on my iPhone 11(iOS 14.6) and then open the app again the play button doesn't work, nothing happens when I press it.

I get this error message:
```
2022-02-07 12:27:57.601921+0100 appname[1760:1305811] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Error when sending event: remote-duck with body: {
  paused = 1;
}. RCTCallableJSModules is not set. This is probably because you've explicitly synthesized the RCTCallableJSModules in RNTrackPlayer, even though it's inherited from RCTEventEmitter.'
*** First throw call stack:
(0x1a847a754 0x1bcf417a8 0x1a837c3f8 0x1a97a3a6c 0x10096e770 0x100cbd700 0x100cbddd8 0x1a83d56d4 0x1a83d567c 0x1a83d4be8 0x1a83d45a8 0x1a96d96ac 0x1afe84528 0x1afe7d6ac 0x104a480b4 0x104a49de0 0x104a5a0a8 0x1a83f4398 0x1a83ee270 0x1a83ed360 0x1bfa2b734 0x1aae68584 0x1aae6ddf4 0x100414710 0x1a80a9cf8)
libc++abi: terminating with uncaught exception of type NSException
terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Error when sending event: remote-duck with body: {
  paused = 1;
}. RCTCallableJSModules is not set. This is probably because you've explicitly synthesized the RCTCallableJSModules in RNTrackPlayer, even though it's inherited from RCTEventEmitter.'
```

**Steps To Reproduce**
1. Clone the example app
2. In `package.json` remove the `postinstall` npm script
3. In `package.json` change `"react-native-track-player": "file:.."` to `"react-native-track-player": "2.1.2",`
4. Install and run the app
5. Press the play button
6. Press the pause button
6. Lock the screen
7. Open the app again
8. Press the play button

**Code To Reproduce**
N/A

**Environment Info:**
```
System:
    OS: macOS 11.6.2
    CPU: (4) x64 Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
    Memory: 71.57 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.18.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.65.1 => 0.65.1
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
Track Player version: 2.1.2
Real device, iPhone 11
iOS version: 14.6

**How I can Help**
Might be able to dig deeper in the future if the maintainers aren't able to fix it and the client wants it.

**Comment by DennisdeWitNL** [comment]
I have the same problem.

**Comment by jspizziri** [comment]
@janlonden ,

I recently noticed some strange behaviour with the play/pause button in the example app caused by a missing dependency in a [callback hook which I've fixed here](https://github.com/doublesymmetry/react-native-track-player/pull/1473/commits/a91461f10ef6d3c1bdad0d6ece4e707e08d94054). I believe this is the root of the issue you were seeing. I've attempted to reproduce this behavior with the fix I linked to you in place and everything works. I'm going to close this issue as I believe it to be the cause and I can't reproduce it.

If this doesn't solve your issue please:

1. Update to `v2.2.0-rc3`
2. Create a repo that demonstrates the issue you're seeing consistently.

**Comment by iboxgithub** [comment]
Hi @jspizziri , 
as you can see below I still have the issue. 
Could I grant you access to my repo (private) for you to try to find the issue?
<img width="889" alt="image" src="https://user-images.githubusercontent.com/5391993/174086997-69d02c9e-915b-44f2-8ebe-100ad86038dd.png">

**Comment by jspizziri** [comment]
@iboxgithub , can you please try to reproduce it with the example app?

**Comment by iboxgithub** [comment]
unfortunately I can't :( 
it must be something related to the OS (MacOS in my case) but can't see what despite looking for it...tbh I saw several people having this issue so there is definitely something to dig in... I know it's annoying without being able to reproduce it on your environment... if you want I am totally down to do a video call with remote access to try to resolve this once and for all..cause tbh it's a bit scary as I would like to push an app in Production with this lib...and I don't know why/how the behavior could have changed...

**Comment by iboxgithub** [comment]
@jspizziri I just found a way to make the app work again, the issue is gone (no clue) how: I reinstalled the app on my simulator (so I deleted it then ran expo run:ios again)
so, good for my dev environment but still a bit scary for when I will want to deploy live as app updates over the air won't solve the issue and I would definitely have to ask customers to delete then re-install the app :(
With that in mind: would you (or someone else for the team) be up for a live debug when this happens again? in order to strengthen the lib

**Comment by jspizziri** [comment]
@iboxgithub I'm open to live debugging it if it happens again (assuming that it happens at a time that I'm available).

**Comment by iboxgithub** [comment]
I don't unfortunately (otherwise I would have posted it here I know it's WAY easier). The only thing I can do now is to use 2 of my commits to reproduce it (I can still give you the instructions on how I reproduce it locally, will have to grant you access to a private repo)

**Comment by fivecar** [comment]
Hit this issue in my production app just yesterday, running react-native-track-player@^3.2.0. Don't know how it was hit, but it's definitely still happening:

<img width="446" alt="image" src="https://github.com/doublesymmetry/react-native-track-player/assets/39933441/c0110507-00d0-4246-a181-cf3d263e6e28">

@jspizziri : although I don't have a reliable repro yet (much less in the example app, since this likely takes a confluence of things to make happen), should we potentially keep this issue open, since it's still a real issue that's being hit in the wild on the 3.2.0?
