### ISSUE TITLE
eas build crash in some android devices

### ISSUE THREAD

**Issue by anti-duhring** [doublesymmetry/react-native-track-player#1588]
**Describe the Bug**
My app crash in some devices when I install and run the apk using `eas build`, but when I install the same apk in the android device that I used to develop the prebuild version it works fine... My guess is that the problem is in the build.gradle, because my prebuild version only works when I put `jcenter()` inside the build.gradle file.

I saw #1573 issue, but I don't know if is the same problem and my `react-native-track-player` version is `2.1.3`.

I got this error in my logcat:
```
06-30 17:36:29.157 13688 14145 E ReactNativeJS: TypeError: null is not an object (evaluating 't.RATING_HEART')
```

**Steps To Reproduce**
- Create a new project 
- Setup the track player
- Run `eas build:android`

**Environment Info:**
System:
    OS: Windows 10 10.0.22000        
    CPU: (4) x64 11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz
    Memory: 474.42 MB / 3.73 GB      
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.7.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 29, 30, 31, 32 
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0 
      System Images: android-25 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom      
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8309675    
    Visual Studio: Not Found
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.68.2 => 0.68.2   
    react-native-windows: Not Found  
  npmGlobalPackages:
    *react-native*: Not Found

**How I can Help**
I'm right now trying to figure out why the app doesn't crash in my android device, I hope to figure out soon.

**Comment by anti-duhring** [comment]
Fixed by updating to version `2.2.0-rc4`

**Comment by dangnguyen1004** [comment]
Why i removed the library but this error still exist in file android/app/src/main/assets/index.android.bundle
