### ISSUE TITLE
Queue End Reached firing too early on iOS

### ISSUE THREAD

**Issue by rpadilla6** [doublesymmetry/react-native-track-player#1598]
**Describe the Bug**
Hi there, I'm writing some functionality to track when a queue has ended in order to reset to the beginning of the first track. I ran into an issue where if the queue is longer than one track, the `PlaybackQueueEnded` is fired too early, which breaks the experience for me on iOS. This is not the case on Android.

**Steps To Reproduce**

1. Add tracks to a queue, (minimum of two)
2. Play first track, you can seek to the end of it to go faster.
3. When that song finishes, you can see that the track player event `PlaybackQueueEnded` gets fired on iOS.

**Code To Reproduce**
```
useTrackPlayerEvents([Event.PlaybackQueueEnded], async (queueEndedPayload) => {
    console.log({ queueEndedPayload });
  });
```

**Environment Info:**
Paste the results of `npx react-native info`:
```
System:
    OS: macOS 12.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 261.01 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.18.0 - ~/.nvm/versions/node/v14.18.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 23, 25, 26, 28, 29, 30, 31
      Build Tools: 26.0.3, 27.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.2, 31.0.0, 32.0.0
      System Images: android-26 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.12 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.1 => 0.68.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
 ```
Paste the exact `react-native-track-player` version you are using: 2.2.0-rc3
Simulator: iPhone 13 15.5
What OS are you running? Mac OS 12.4

I briefly looked into the Swift file contains  this function and added some logging, and it seems like by the time the QueuePlayer gets the `playedUntilEnd` reason, nextItems is already 0.

```
func handleAudioPlayerPlaybackEnded(reason: PlaybackEndedReason) {
        print("Reason",reason)
        print("Next Items", player.nextItems.count)
        // fire an event for the queue ending
        if player.nextItems.count == 0 && reason == PlaybackEndedReason.playedUntilEnd {
            sendEvent(withName: "playback-queue-ended", body: [
                "track": player.currentIndex,
                "position": player.currentTime,
            ])
        }

        // fire an event for the same track starting again
        if player.items.count != 0 && player.repeatMode == .track {
            handleAudioPlayerQueueIndexChange(previousIndex: player.currentIndex, nextIndex: player.currentIndex)
        }
    }
```
Resulting logs from playing a queue of two tracks:

```
// Started playing, immediately get the following which I find odd anyway
Reason playerStopped
Next Items 1
// After the previous track finishes and skips to the next one
Reason playedUntilEnd
Next Items 0
```
I don't know too much about iOS development but thought I'd put it here if anyone knew anything about it or noticed this issue. I was initially hoping for an event to fire when a track itself has finished but I don't believe that exists.

**Comment by jsallstrom** [comment]
Im having exactly the same problem

**Comment by jspizziri** [comment]
We just merged a PR (https://github.com/doublesymmetry/react-native-track-player/pull/1501) that addressed multiple issues with the PlaybackQueueEnded event on both Android and iOS. I tested that PR just now and this issue did not occur, so the PR must've solved it.

You can verify by cloning down the repo and installing and running the example project.

**Comment by rpadilla6** [comment]
@jspizziri Can we reopen this? I've tested on the latest version of 3.1.0 and I have verified it is still occurring on a physical iPhone 11 running iOS 16. Is it just a matter of QueueEndReached firing once the last track has been reached on iOS, making it function differently than Android?

**Comment by jspizziri** [comment]
@rpadilla6 I just reread your issue, so what behavior are you actually expecting? And how exactly does that currently diverge from Android?

**Comment by rpadilla6** [comment]
@jspizziri The behavior I'm expecting is what I experience on android, if I add several tracks to the queue, say three tracks, all of them will play through completely and then the QueueEnded event will fire once the last track has completed. On iOS, it's slightly confusing since the QueueEnded event fires as I would expect when it is a single item, that being that it fires when the track completes. However, when there are two or more tracks in the queue, the event triggers when the last track begins playing, or so it seems. I've been using the event to reset the play queue to a particular point, like go to the first track and set the position to 0, but that doesn't work well if it doesn't allow me to play the whole queue on iOS.

**Comment by jspizziri** [comment]
@rpadilla6 I was just able to reproduce your findings. This is quite strange. I'll be looking into this very son.

**Comment by jspizziri** [comment]
My findings seem to be that a queue ended event fires once on the second-to-last item in the queue, and then again once the queue actually ends.

**Comment by sachin36987** [comment]
If somebody is still facing the issue of dual firing of PlayBackQueueEnded on IOS, then try code below:
`if (sIOS()) {
          TrackPlayer.getState().then(state => {
            if (state === State.Paused) {
              // IOS Ended.
            }
          });
        } else {
          // Android ended.
        }`

**Comment by parthkanani93** [comment]
> If somebody is still facing the issue of dual firing of PlayBackQueueEnded on IOS, then try code below: `if (sIOS()) { TrackPlayer.getState().then(state => { if (state === State.Paused) { // IOS Ended. } }); } else { // Android ended. }`

Thanks It works
