### ISSUE TITLE
3.1.0 does not fire events in background service on Android when tapping play/pause buttons in notification

### ISSUE THREAD

**Issue by doughsay** [doublesymmetry/react-native-track-player#1657]
**Describe the Bug**

The player background service does not receive remote events when buttons are tapped in the Android notification. Events tested include: RemotePlay, RemotePause, RemoteJumpBackward, and RemoteJumpForward.

To be clear: tapping the play/pause or jump buttons *does* do the correct actions (i.e. it actually pauses or plays, etc). It just doesn't dispatch an event to the background service, so we can't perform any side-effects.

**Steps To Reproduce**

1. Modify the example app to add `console.log` statements in the `Remote*` event handlers in `src/services/PlaybackService.ts`.
2. Install/launch the example app on Android and start playing a track
  a. note that you see the log output
3. Press the pause icon in the Android notification
  a. note that you do not see the log output

**Code To Reproduce**

The existing example app is enough to reproduce the issue.

**Environment Info:**

```
System:
    OS: Linux 5.19 Pop!_OS 22.04 LTS
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
    Memory: 18.22 GB / 31.26 GB
    Shell: 3.3.1 - /usr/bin/fish
  Binaries:
    Node: 16.13.1 - ~/.asdf/installs/nodejs/16.13.1/bin/node
    Yarn: 1.22.19 - ~/.asdf/installs/nodejs/16.13.1/.npm/bin/yarn
    npm: 8.1.2 - ~/.asdf/plugins/nodejs/shims/npm
    Watchman: 4.9.0 - /usr/bin/watchman
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: AI-212.5712.43.2112.8815526
  Languages:
    Java: 11.0.16 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^18.0.0 => 18.2.0
    react-native: ^0.69.0 => 0.69.4
  npmGlobalPackages:
    *react-native*: Not Found
```

Paste the exact `react-native-track-player` version you are using:

```
3.1.0
```

Real device? Or simulator?: **Real device**

What OS are you running?: **Android 12**

**How I can Help**

I can help by testing PRs; I do not have enough Kotlin knowledge to be effective in actually working in KotlinAudio.

**Comment by Hannes1** [comment]
It's working on both my devices, running android 12 and android 9

**Comment by doughsay** [comment]
@Hannes1 your example would not reproduce the bug as described.  Your event handlers don't perform any side-effects.  The play, pause, and jump events will appear to be working for you because all you're doing is the default action.  If you add a `console.log` or some other side-effect into your handlers you will see that the handlers never actually execute.

**Comment by mpivchev** [comment]
This PR will provide the fixes: https://github.com/doublesymmetry/react-native-track-player/pull/1668

**Comment by elirangoshen** [comment]
it also not working for me in ios.
same issue

**Comment by jspizziri** [comment]
@elirangoshen please install the `nightly` build. This has been fixed, but hasn't been released anywhere but there yet.

**Comment by elirangoshen** [comment]
> @elirangoshen please install the `nightly` build. This has been fixed, but hasn't been released anywhere but there yet.

it still doesn't work in ios. and i think that the fix on this thread is only related to android files not ios.

**Comment by mpivchev** [comment]
@elirangoshen Currently we are not super active on the iOS side, as we are trying to make the Android side more stable and fix high priority issues. Also, this issue has been opened particularly for Android and if there is an issue with iOS, please open a new ticket.

**Comment by jspizziri** [comment]
@mpivchev I'm working with @elirangoshen on [a separate issue](https://github.com/doublesymmetry/react-native-track-player/issues/1712).
