### ISSUE TITLE
State.Ready is returned by getPlaybackState instead of State.Playing even though the player is playing (iOS only)

### ISSUE THREAD

**Issue by mitchdowney** [doublesymmetry/react-native-track-player#1898]
**Describe the Bug**

When the player is playing an audio file, and I call the `seekTo` method, then afterwards the `TrackPlayer.getPlaybackState()` method returns `State.Ready`, and the `Event.PlaybackState` listener is called with the `State.Ready` event, but is never called with `State.Playing` even though the player resumes playing after seek.

We rely on the  `TrackPlayer.getPlaybackState()` method to tell us whether or not the player is currently playing, but when it gets stuck on `State.Ready` even though it is currently playing, how can we determine it is actually currently playing?

**Steps To Reproduce**
I can get to this later if needed. I mostly want to know is this expected behavior with an alternative solution, or a bug?

**Code To Reproduce**
I can get to this later if needed.

**Replicable on Example App?**
I can get to this later if needed.

**Environment Info:**
```
System:
    OS: macOS 13.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Memory: 510.98 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
    Yarn: 1.22.18 - ~/.yarn/bin/yarn
    npm: 6.14.17 - ~/Repos/podverse-rn/node_modules/.bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8512546
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.9 - /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.66.5 => 0.66.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Paste the exact `react-native-track-player` version you are using:
3.2.0-480f64932969545fe38a261fb3867f90f514478c

Real device? Or simulator?
Both

What OS are you running?
iOS 16.2

**How I can Help**
I can try to debug it, but I was hoping to gather information from a core dev or @puckey in case this is a known issue, or an issue with a simple workaround solution.

**Comment by mitchdowney** [comment]
It seems like the `Event.PlaybackState === State.Ready` only gets fired on iOS, and when you seekTo a position beyond what is currently buffered. I am inferring this because `State.Ready` event is not fired every time I seekTo, but it does seem to fire consistently when I start playing a long podcast, and then seekTo near the end of the show.

I guess maybe the issue would like in SwiftAudioEx since Android appears to return the `State.Playing` event every time I would expect it to...

**Comment by mitchdowney** [comment]
I was able to reproduce the issue on the iOS example app by adding this track to the beginning of the playlist.json:

```
  {
    "url": "https://op3.dev/e/mp3s.nashownotes.com/PC20-118-2023-01-20-Final.mp3",
    "title": "Episode 118",
    "artist": "Podcasting 2.0",
    "artwork": "https://noagendaassets.com/enc/1601061118.678_pciavatar.jpg",
    "duration": 1000
  },
```

Then I start playing the episode...then I seekTo a time near the end of the episode. The `ready` event fires, but a `playing` event is not subsequently fired.

**Comment by puckey** [comment]
While I have been able to reproduce this issue, I haven't been able to find a solution yet.

For some reason (AVPlayer. timeControlStatus)[https://developer.apple.com/documentation/avfoundation/avplayer/1643485-timecontrolstatus] is not changing to (AVPlayer.TimeControlStatus.waitingToPlayAtSpecifiedRate)[https://developer.apple.com/documentation/avfoundation/avplayer/timecontrolstatus/waitingtoplayatspecifiedrate] after the seek to indicate buffering and back to (AVPlayer.TimeControlStatus.playing)[https://developer.apple.com/documentation/avfoundation/avplayer/timecontrolstatus/playing] to indicate the resumption of playing.

**Comment by ouabing** [comment]
I'm storing the playback state in my app, and synchronizing the playback like this as a workaround:
```
const onPlaybackStateChange = (data) => {
  const { state } = data

  // WORKAROUND: on iOS, playback state goes like playing -> ready, ignore here
  if (
    Platform.OS === 'ios' &&
    someLocalStorage.playbackState === PlayState.Playing &&
    state === PlayState.Ready
  ) {
    return
  }

  someLocalStorage.playbackState = state
}

TrackPlayer.addEventListener(Event.PlaybackState, (data) => {
  onPlaybackStateChange(data)
})
```

It's ok for me because I'm using redux, I need to sync the state in my redux store to keep UI updated.

**Comment by ouabing** [comment]
My observation is the playback state always goes like Playing -> Ready, so if you don't care about Ready state, you can just sync the playback state in your own local storage(like redux), and ignore the ready state:

```
const onPlaybackState = (data: PlaybackStateEvent) => {
  if (data.state === PlayState.Ready) {
    return
  }
  someLocalStorage.playbackState = data.state
}

TrackPlayer.addEventListener(Event.PlaybackState, (data) => {
  onPlaybackState(data)
})
```

**Comment by mitchdowney** [comment]
@ouabing thanks, that makes sense. We're doing something similar to that. It's a little inconvenient that getPlaybackState doesn't always return State.Playing when it is playing, but you're right we can work around the issue.

**Comment by puckey** [comment]
A stopgap solution would be to skip setting the state to `PlayState.Ready` when the state is already `PlayState.Playing` since it ought to be impossible to go from playing to ready. In which case the play state would just stay at `PlayState.Playing`

**Comment by mitchdowney** [comment]
Since it sounds like there are simple workarounds, feel free to close this as wontfix. Thanks for your help!

**Comment by puckey** [comment]
I would prefer to keep this issue open as it is indeed unexpected behavior

**Comment by puckey** [comment]
This should be fixed by the following SwiftAudio pr: https://github.com/doublesymmetry/SwiftAudioEx/pull/40

**Comment by jeroenptrs** [comment]
@dcvz @puckey Can we reopen this issue? I'm still seeing `State.Ready` being set after `State.Playing` has already occurred. I'm on the latest nightly ([3.2.0-bb749e5d286737681ba8907dfd287480eb1cec45](https://www.npmjs.com/package/react-native-track-player/v/3.2.0-bb749e5d286737681ba8907dfd287480eb1cec45)) and I'm seeing this on 2 different occasions:

* `playWhenReady` is `true` and `TrackPlayer.load(track)` is used. In the following code snippet:
```
await TrackPlayer.setPlayWhenReady(true);
await TrackPlayer.load(track);
```
the trackstate occasionally moves from `State.Playing` to `State.Ready`. It appears to be a race condition because I only sometimes get it.
* `State.Paused` moves to `State.Ready` after returning from background: when I leave the app in foreground, load a track and pause it, lock my phone and wait a few minutes, then unlock my phone with the app back in foreground, the state shifts to be `State.Ready`.

Both appear to happen on iOS at the very least.

**Comment by puckey** [comment]
@dcvz it is unclear if this pr already made it into nightly.. can you confirm?

**Comment by DennisdeWitNL** [comment]
@puckey Seems it didn't. I have the latest nightly, but it shows the following:

` LOG  {"state": "loading"}
 LOG  {"state": "buffering"}
 LOG  {"state": "playing"}
 LOG  {"state": "ready"}
 LOG  {"state": "ready"}
 LOG  {"state": "ready"}
 LOG  {"state": "ready"}
 LOG  {"state": "ready"}
 LOG  {"state": "ready"}
 LOG  {"state": "ready"}
 LOG  {"state": "ready"}
 LOG  {"state": "ready"}
 LOG  {"state": "ready"}
 LOG  {"state": "ready"}
 LOG  {"state": "ready"}
 LOG  {"state": "ready"}
 LOG  {"state": "ready"}
 LOG  {"state": "ready"}
 LOG  {"state": "ready"}
 LOG  {"state": "ready"}
 LOG  {"state": "ready"}
 LOG  {"state": "ready"}
 LOG  {"state": "ready"}
 LOG  {"state": "ready"}
 LOG  {"state": "ready"}
 LOG  {"state": "ready"}
 LOG  {"state": "ready"}
 LOG  {"state": "ready"}
 LOG  {"state": "ready"}
 LOG  {"state": "ready"}
`

There is sound, just the state doesn't update.

**Comment by puckey** [comment]
@DennisdeWitNL  @jeroenptrs can either of you reproduce this with the RC release?

**Comment by DennisdeWitNL** [comment]
@puckey Sure, will check later today. It is good to know that I have tested this with a live stream.

**Comment by DennisdeWitNL** [comment]
@puckey Ok, but I will first need to do some reinstalls on my Mac Studio. I normally develop on my MacBook Pro, but I broke the screen. So it has to be repaired. :-))

**Comment by jeroenptrs** [comment]
@puckey yes I still see at least the second reproduction method (pausing, locking screen for a few minutes and unlocking going back to the app) happening again. I'm trying to reproduce the first but it was with flaky results in the past as well so I'm not confident I'll easily be able to reproduce it

**Comment by jeroenptrs** [comment]
@puckey I'm able to reproduce the following on the example app as well, I unfortunately cannot provide logs because going to lockscreen disables metro transport but the steps are as follows:

1. Add trackstate to TrackInfo.tsx
2. Start playing the app, then pause
3. Lock the screen and wait a bit
4. Unlock the screen, with the example app now in foreground
5. Trackstate should now be "ready"

I'm aware this technically doesn't apply to the issue as this is focused on `State.Playing`, but I'd expand the issue to also include `State.Paused`

**Comment by DennisdeWitNL** [comment]
@puckey The RC-version shows 'ready' before 'playing', straight after 'buffering'.

```
 LOG  {"state": "loading"}
 LOG  {"state": "loading"}
 LOG  {"state": "loading"}
 LOG  {"state": "loading"}
 LOG  {"state": "buffering"}
 LOG  {"state": "ready"}
 LOG  {"state": "playing"}
 LOG  {"state": "playing"}
 LOG  {"state": "stopped"}
 LOG  {"state": "stopped"}
 LOG  {"state": "stopped"}
```

**Comment by puckey** [comment]
Okay cool, so this looks to be working as intended.

@jeroenptrs If you want to know whether playback is paused or not you probably want to use the newly introduced `TrackPlayer.getPlayWhenReady()`

Also check https://github.com/doublesymmetry/react-native-track-player/blob/main/example/src/components/PlayPauseButton.tsx

**Comment by jeroenptrs** [comment]
> Okay cool, so this looks to be working as intended.
> 
> @jeroenptrs If you want to know whether playback is paused or not you probably want to use the newly introduced `TrackPlayer.getPlayWhenReady()` / `usePlayWhenReady()`
> 
> Also check https://github.com/doublesymmetry/react-native-track-player/blob/main/example/src/components/PlayPauseButton.tsx

The example doesn't 100% translate to the approach I have but I managed to make it work, I'll be validating this approach tomorrow and will let you know if anything pops up. Thanks for the follow up!
