### ISSUE TITLE
Android: Track Player still in memory and notification still visible after App Kill (Google Pixel 4a)

### ISSUE THREAD

**Issue by zerobertelprivat** [doublesymmetry/react-native-track-player#1927]
**Describe the Bug**

After killing my app a second and more times, the desired behavior "player stops and notification is removed"
is disappeared

**Steps how i Reproduce the behavior**
Open the app, start the player and kill the app.
-> app is closed, notification is gone, app is not marked as active
Open app again, start player again, kill app again
-> app is closed, but player is still playing, notification is still visible, app is marked as active

This behavior stays the same, until i close the app manually in the system modal

**Code To Reproduce**
The player is initialized via a context provider:

export const PodcastPlayerProvider = ({
    children,
}: {
    children: React.ReactNode;
}) => {
    ...
    useEffect(() => {
        const init = async () => {
            await TrackPlayer.setupPlayer({
                iosCategory: IOSCategory.Playback,
                iosCategoryMode: IOSCategoryMode.SpokenAudio,
                iosCategoryOptions: [
                    IOSCategoryOptions.DuckOthers,
                    IOSCategoryOptions.AllowAirPlay,
                    IOSCategoryOptions.AllowBluetooth,
                ],
            }).catch(() => {});
            await TrackPlayer.updateOptions({
                forwardJumpInterval: PODCAST_FORWARD_SEC,
                backwardJumpInterval: PODCAST_REWIND_SEC,
                android: {
                    appKilledPlaybackBehavior: AppKilledPlaybackBehavior.StopPlaybackAndRemoveNotification,
                },
                capabilities: [
                    Capability.Play,
                    Capability.Pause,
                    Capability.SkipToNext,
                    Capability.SkipToPrevious,
                    Capability.SeekTo,
                    Capability.JumpForward,
                    Capability.JumpBackward,
                ],
                notificationCapabilities: [Capability.Play, Capability.Pause],
                compactCapabilities: [Capability.Play, Capability.Pause],
            });
        };
        init();
    }, []);
   ...
}

**Environment Info:**
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 104.00 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
    Yarn: 1.22.19 - ~/Projekte/Mediapioneer/app/node_modules/.bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
    Watchman: 2022.12.12.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.0 => 0.70.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

react-native-track-player version: 3.2.0 
Device: Google Pixel 4a, Android 13

**Comment by smn-snkl** [comment]
We're experiencing the same. We're having a hard time at the moment to find a version of the RNTP that doesnt:
- Continue on app kill or
- Keep the app active in background all the time or
- Continue playing a stopped track after an interruption

Any help is greatly appreciated :)

**Comment by jspizziri** [comment]
@smn-snkl @zerobertelprivat can you please try in `nightly`? There was a PR we merged recently that impacts this but I'm not sure if it solves your issue:  https://github.com/doublesymmetry/react-native-track-player/commit/e6adb3e72a418f00f21784272a9a52820e6674f4

**Comment by smn-snkl** [comment]
We are on nightly now, but were a bit worried whether nightly is properly QA'ed?

**Comment by puckey** [comment]
We are indeed in the process of QAing nightly – it should be released as 4.0 in the coming weeks. Are you able to replicate this issue still in `nightly` or is it fixed?

**Comment by smn-snkl** [comment]
It seems to be fixed, we're slowly rolling it out after doing some internal QAing. If you don't hear back from us within the next week, consider it fixed from our side :)

**Comment by puckey** [comment]
Seemingly fixed in `nightly`.

**Comment by zerobertelprivat** [comment]
Hello guys, sorry for my quietness. But thank you both for checking this issue, i am looking forward for v 4.0 :)

**Comment by SAHITYASAI** [comment]
did anyone succeed in finding solution to this issue? I'm still facing this issue in v4.0.0-rc04. Any help is greatly appreciated.

**Comment by zerobertelprivat** [comment]
Our solution was to build a custom player for android

**Comment by SyedTayyabUlMazhar** [comment]
If anyone is still looking for a solution, have a look at [this](https://github.com/doublesymmetry/react-native-track-player/issues/1759#issuecomment-1319985067)
