### ISSUE TITLE
The methods such as 'getSleepTimerProgress' have not been implemented

### ISSUE THREAD

**Issue by GentleCai-CH** [doublesymmetry/react-native-track-player#2477]
**Describe the Bug**

**An error occurred while executing Yarn iOS:**

WARN  The objective-c `getSleepTimerProgress:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject` method signature for the JS method `getSleepTimerProgress` can not be found in the ObjecitveC definition of the TrackPlayerModule module.
The `getSleepTimerProgress` JS method will not be available.
WARN  The objective-c `setSleepTimer:(double)time resolver:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject` method signature for the JS method `setSleepTimer` can not be found in the ObjecitveC definition of the TrackPlayerModule module.
The `setSleepTimer` JS method will not be available.
WARN  The objective-c `sleepWhenActiveTrackReachesEnd:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject` method signature for the JS method `sleepWhenActiveTrackReachesEnd` can not be found in the ObjecitveC definition of the TrackPlayerModule module.
The `sleepWhenActiveTrackReachesEnd` JS method will not be available.
WARN  The objective-c `clearSleepTimer:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject` method signature for the JS method `clearSleepTimer` can not be found in the ObjecitveC definition of the TrackPlayerModule module.
The `clearSleepTimer` JS method will not be available.

**Reason:** 
The 'TrackPlayerModule' was called on the JS side` getSleepTimerProgress`、`setSleepTimer`、`sleepWhenActiveTrackReachesEnd`、`clearSleepTimer`  Waiting for methods, but no corresponding implementation (method signature) was found in the iOS native module (Objective C/Swift).

**Comment by GentleCai-CH** [comment]
`react-native-track-player@4.1.1`

**Comment by jspizziri** [comment]
@GentleCai-CH this should be addressed in https://github.com/doublesymmetry/react-native-track-player/pull/2478

**Comment by Licheung228** [comment]
> [@GentleCai-CH](https://github.com/GentleCai-CH) this should be addressed in [#2478](https://github.com/doublesymmetry/react-native-track-player/pull/2478)


still exist

<img width="856" height="409" alt="Image" src="https://github.com/user-attachments/assets/a6f3f94b-d325-4454-83e0-e3a429e30952" />

**Comment by GentleCai-CH** [comment]
这是来自QQ邮箱的自动回复邮件。你好，你所发送的邮件我已收到，待查阅后必要时我会回复。请耐心等待。

**Comment by jspizziri** [comment]
@GentleCai-CH , the aforementioned fix is not in `v4.1.2`, it's in `v5.0.0-alpha0`.

**Comment by Licheung228** [comment]
> [@GentleCai-CH](https://github.com/GentleCai-CH) , the aforementioned fix is not in `v4.1.2`, it's in `v5.0.0-alpha0`.

thx, I try now, is available.
