### ISSUE TITLE
Some functionality doesn't work on v5.0.0-alpha0

### ISSUE THREAD

**Issue by bahmanworld** [doublesymmetry/react-native-track-player#2507]
**Describe the Bug**
Some functionality doesn't work on v5.0.0-alpha0

- Remote actions doesn't work on media notification
- capabilities doesn't apply on notification

TrackPlayer`(newArch)` works fine but not as expected like v4.1.1

**Environment Info:**
Expo SDK 54@beta
TrackPlayer 5.0.0-alpha0
Device: Real Device
Platform: Android 12

Any further updates soon?

**Comment by anultravioletaurora** [comment]
Confirming that I'm running into this issue on the `5.0.0` alpha build

[Related Jellify issue](https://github.com/Jellify-Music/App/issues/482)

I'll get this reproduced in the example repo 👍

**Comment by jspizziri** [comment]
@bahmanworld ,

> I couldn't reproduce the example repo

Does that mean you've successfully tested the example app and that it's working there? Or does it mean you couldn't successfully run the example app.

**Comment by lovegaoshi** [comment]
like i said i CANNOT REPRODUCE on S21 + android 14. you have to give more details as the device and android version.

https://github.com/user-attachments/assets/5513358c-b961-4fd3-83d6-d51a06a082b2

**Comment by sohamnakhare** [comment]
@lovegaoshi Interestingly it is working for me in the emulator but not on the device.  I'm running it on One Plus Nord 2T.

**Comment by lovegaoshi** [comment]
this is quickly turning into a device specific problem which nobody here
can help. since u have the buggy device pls follow what i posted above: is
onMediaButtonEvent firing and if so whats the intent.

**Comment by sohamnakhare** [comment]
@lovegaoshi it is not working on many Android devices.

@jspizziri I'm able to reproduce the issue on the example in the repo. 

Attaching the google drive link of the APK -> https://drive.google.com/file/d/1x6D3FrlERXUvboo-d3HGKHauYHbF8BoT/view

I ran this on android 14 device.

**Comment by lovegaoshi** [comment]
did i not post a video i CANNOT REPRODUCE on s21 + android 14? chanting the
same thing will get nowhere unless u somehow make it reproducible on my
device, or u answer my question - is onMediaButtonEvent firing and whats
the intent

**Comment by jspizziri** [comment]
@sohamnakhare ,

I'm not downloading an APK from your Google Drive and installing it. If you modified anything in the `/example` app to get your issue, then you should send me a link to your fork containing your changes (however, I've tested with the `updateOptions` config that you sent above and still can't repro)

Lastly, as @lovegaoshi has already indicated an inability to reproduce it on another device with Android 14 installed. I'm also unable to reproduce the issue on my Pixel with Android 16 installed.

At this point, you're either doing something wrong or this is a device-specific issue (as mentioned previously). You're options are:

1. Answer @lovegaoshi's question:

    > is onMediaButtonEvent firing and whats the intent?

2. Send the cash required to purchase your exact device and conduct my own testing on it for you.

**Comment by sohamnakhare** [comment]
<img width="1435" height="225" alt="Image" src="https://github.com/user-attachments/assets/4a94b685-6565-4ef3-9a2c-fabeca60a125" />
<img width="1446" height="462" alt="Image" src="https://github.com/user-attachments/assets/86cca1eb-5960-4549-9827-7f4f29d157de" />

@jspizziri @lovegaoshi I got the lock screen controls  working by adding the code above.

How can we handle this better ?

**Comment by lovegaoshi** [comment]
open a PR then


===


whats described here is pretty interesting - the added code is actually an oversight from main that [they didnt copy from my branch](https://github.com/lovegaoshi/react-native-track-player/blob/b638e55bc11c213082502399f4a2ae83ab1d3a0d/android/src/main/java/com/doublesymmetry/trackplayer/service/MusicService.kt#L329). whats commented out, as you can see from my HACK comment above, is specific for android <13 - notification calls onStartCommand but not onMediaButtonEvent. 

I'm starting to think ur seeing is, while still a device specific problem, ur device OEM never adapted the android 13 notification style. Unfortunately the only 1+ device i have is a 1+ 7 /android 12 which will be caught by the if i wrote there. other than be cautious not to call onMediaKeyEvent on my pixel devices twice it seems safe enough.

**Comment by jspizziri** [comment]
@sohamnakhare ill leave it to you to open a PR for this.

**Comment by zeevenn** [comment]
same issue on Android 15

**Comment by jspizziri** [comment]
@zeevenn try adding this to your local Kotlin in node_modules:

https://github.com/doublesymmetry/react-native-track-player/issues/2507#issuecomment-3263616306

**Comment by tomKFM** [comment]
Hey there, same issue here. Adding the above code from @sohamnakhare did solve the issue.

**Comment by jspizziri** [comment]
@Tom-KAUFFMANN would love a PR

**Comment by sohamnakhare** [comment]
@jspizziri I have raised a PR.

**Comment by tomKFM** [comment]
I think @sohamnakhare is already working on it [here](https://github.com/doublesymmetry/react-native-track-player/pull/2517)

**Comment by NeverGET** [comment]
I also have similar problem, I fixed with AI and i want to share with you. First of all i need explain why/how i am using this package.

I am making an app for shoutcast radio station live media player, so my audio will be streaming and live, also i had to update now playing info on native media controller. The Play/Pause button does not work with the streaming, and i tried others solutions too. finally fixed, and down below there is a documentaiton for how you reproduce my fix:

# React Native Track Player Setup Guide

## Problem Overview

When implementing `react-native-track-player` v4.1.2 for audio streaming, media controller play/pause buttons in the notification shade and lock screen were not functioning, even though:
- Media controls were visible in notification and lock screen
- Now playing metadata was displaying correctly
- The PlaybackService was properly registered

Pressing play/pause buttons on the media controller had no effect on playback.

## Root Cause Analysis

### The Issue

react-native-track-player's default configuration uses:
```kotlin
interceptPlayerActionsTriggeredExternally = true
```

This setting intercepts all media control actions (play, pause, next, previous, stop) and routes them through JavaScript via HeadlessJsTaskService. The flow is:

1. User presses play/pause on media controller
2. MediaSession receives the action
3. Action is intercepted (not executed)
4. Event is emitted to JavaScript via ReactContext
5. JavaScript handles the event and calls native methods

**The problem**: This flow fails when ReactContext is null, which commonly occurs:
- During service startup
- When app is backgrounded
- Before React Native is fully initialized

### Evidence from Logs

```
10-02 19:37:40.850 D MusicService: Media control event received: MediaSessionCallback$PAUSE
10-02 19:37:40.850 D MusicService: Emitting BUTTON_PAUSE (remote-pause) event
10-02 19:37:40.851 E MusicService: ReactContext is null, cannot emit event: remote-pause
```

The events were being received and emitted, but couldn't reach JavaScript.

## The Solution

### Architecture Change

Change the architecture to match `expo-video`'s approach: let the underlying MediaSession handle standard actions automatically rather than routing through JavaScript.

**Key Configuration Change** in `MusicService.kt:144`:

```kotlin
// BEFORE (BROKEN)
val playerConfig = PlayerConfig(
    interceptPlayerActionsTriggeredExternally = true,  // Routes to JavaScript
    handleAudioBecomingNoisy = true,
    handleAudioFocus = true
)

// AFTER (FIXED)
val playerConfig = PlayerConfig(
    interceptPlayerActionsTriggeredExternally = false,  // Let MediaSession handle automatically
    handleAudioBecomingNoisy = true,
    handleAudioFocus = true
)
```

### How It Works

With `interceptPlayerActionsTriggeredExternally = false`:

1. User presses play/pause on media controller
2. MediaSession receives the action
3. MediaSession **automatically executes** the action on the player
4. Playback state changes immediately
5. Events are still emitted to JavaScript (when ReactContext is available) for app logic

This approach:
- ✅ Works immediately, even when ReactContext is null
- ✅ Provides responsive media controls
- ✅ Still allows JavaScript to react to events when available
- ✅ Matches the architecture used by expo-video

## Step-by-Step Implementation

### 1. Modify MusicService.kt

**File**: `node_modules/react-native-track-player/android/src/main/java/com/doublesymmetry/trackplayer/service/MusicService.kt`

**Line 144**, change the PlayerConfig:

```kotlin
val playerConfig = PlayerConfig(
    interceptPlayerActionsTriggeredExternally = false,  // Changed from true
    handleAudioBecomingNoisy = true,
    handleAudioFocus = true
)
```

### 2. Create Patch File

```bash
npx patch-package react-native-track-player
```

This creates: `patches/react-native-track-player+4.1.2.patch`

### 3. Verify postinstall Script

Ensure `package.json` has:

```json
{
  "scripts": {
    "postinstall": "patch-package"
  }
}
```

### 4. Rebuild the App

For Expo Development Build:

```bash
npx expo run:android
# or
npx expo run:ios
```

### 5. Test Media Controls

1. Start playing audio
2. Check notification shade - media controls should appear
3. Test play/pause button - should work immediately
4. Test on lock screen - should work
5. Test when app is backgrounded - should work
6. Check that now playing metadata updates correctly

## Comparison with expo-video

### expo-video Architecture

`expo-video` uses `MediaSessionService` with automatic action handling:

```kotlin
// ExpoVideoPlaybackService.kt
class ExpoVideoPlaybackService : MediaSessionService() {
    val mediaSession = MediaSession.Builder(this, player)
        .setCallback(VideoMediaSessionCallback())  // Only for custom commands
        .build()
    // MediaSession handles play/pause automatically
}

// VideoMediaSessionCallback.kt
class VideoMediaSessionCallback : MediaSession.Callback {
    override fun onCustomCommand(...) {
        // Only handles custom commands like seek forward/backward
        // No handling of PLAY/PAUSE - MediaSession does it automatically
    }
}
```

### react-native-track-player (Fixed)

Now uses the same pattern:

```kotlin
// MusicService.kt
val playerConfig = PlayerConfig(
    interceptPlayerActionsTriggeredExternally = false,  // Like expo-video
    // ...
)

// Events still emitted to JavaScript when available
scope.launch {
    event.onPlayerActionTriggeredExternally.collect {
        when (it) {
            MediaSessionCallback.PLAY -> emit(MusicEvents.BUTTON_PLAY)
            MediaSessionCallback.PAUSE -> emit(MusicEvents.BUTTON_PAUSE)
            // ... other events
        }
    }
}
```

## Troubleshooting

### Issue: Media controls not appearing

**Check**:
1. Verify PlaybackService is registered in `app.json`:
```json
{
  "expo": {
    "plugins": [
      [
        "react-native-track-player",
        {
          "playbackServiceName": "PlaybackService"
        }
      ]
    ]
  }
}
```

2. Ensure service is started:
```typescript
await TrackPlayer.setupPlayer();
```

### Issue: Play/pause still not working

**Check**:
1. Verify patch was applied:
```bash
cat node_modules/react-native-track-player/android/src/main/java/com/doublesymmetry/trackplayer/service/MusicService.kt | grep -A2 "val playerConfig"
```

Should show `interceptPlayerActionsTriggeredExternally = false`

2. Rebuild the native app (not just reload):
```bash
npx expo run:android
```

3. Check logs for ReactContext errors:
```bash
adb logcat | grep "ReactContext is null"
```

### Issue: Patch not persisting

**Check**:
1. Verify `postinstall` script runs:
```bash
npm run postinstall
```

2. Check patch file exists:
```bash
ls patches/react-native-track-player+4.1.2.patch
```

3. Ensure `patch-package` is installed:
```bash
npm install --save-dev patch-package
```

## Testing Checklist

- [ ] Media controls appear in notification shade
- [ ] Media controls appear on lock screen
- [ ] Play button works when app is backgrounded
- [ ] Pause button works when app is backgrounded
- [ ] Next/previous buttons work (if applicable)
- [ ] Now playing metadata displays correctly
- [ ] Album art displays correctly
- [ ] Controls work immediately after app launch
- [ ] Controls work after cold boot
- [ ] No "ReactContext is null" errors in logs

## Additional Notes

### Why This Works

The underlying `kotlin-audio` library (QueuedAudioPlayer) and Media3's MediaSession are fully capable of handling playback actions natively without JavaScript. By setting `interceptPlayerActionsTriggeredExternally = false`, we:

1. **Enable immediate response**: MediaSession executes actions directly on the player
2. **Remove dependency on ReactContext**: No need for JavaScript bridge to be ready
3. **Maintain event emissions**: JavaScript still receives events when ReactContext is available
4. **Follow Android best practices**: Native media controls should work natively

### When to Use This Configuration

✅ **Use `interceptPlayerActionsTriggeredExternally = false` when**:
- Building a radio/streaming app where controls must always work
- App needs to work immediately after launch
- Service runs independently of React Native lifecycle
- Following standard Android media app patterns

❌ **Consider `interceptPlayerActionsTriggeredExternally = true` when**:
- Need custom JavaScript logic before every action
- App controls the entire playback lifecycle
- JavaScript is always guaranteed to be running
- Need to intercept and potentially prevent actions

### Future Projects

To reproduce this solution in a new project:

1. Install `react-native-track-player` and `patch-package`
2. Apply the configuration change in `MusicService.kt`
3. Create patch with `npx patch-package react-native-track-player`
4. Commit the patch file to version control
5. Ensure `postinstall` script is configured

This approach is sustainable across library updates - simply reapply the patch after updating react-native-track-player.

## References

- [react-native-track-player GitHub](https://github.com/doublesymmetry/react-native-track-player)
- [expo-video source code](https://github.com/expo/expo/tree/sdk-54/packages/expo-video)
- [Android MediaSession documentation](https://developer.android.com/guide/topics/media/media3/session)
- [kotlin-audio library](https://github.com/doublesymmetry/kotlin-audio)

**Comment by tomKFM** [comment]
@NeverGET I don't get why are you talking about v4 whereas we're trying to fix v5 ? 
v4 worked perfectly for me, the issue appeared on v5

Anyways, i tried to find the interceptPlayerActionsTriggeredExternally and set it to false as you mentionned, but it didn't fix anything for me

**Comment by Jojocaster** [comment]
I'm getting the same issue on my end - at least on a OnePlus 9. I migrated from 4.1.2 to v5, and notifications stopped working. I've just tested on a Pixel and everything seems to be working, but for some reason OnePlus isn't playing ball. 
The notification in the media centre works fine, but not the one on the lockscreen.

**Comment by muhammadhamza841** [comment]
https://github.com/user-attachments/assets/a43029e5-e737-4142-87f7-023be8e9cef1
@jspizziri 
I deployed the example code on a OnePlus 9 running Android 14, and I'm encountering an issue where the notification controller is not working as expected.

I've attached a video demonstrating the problem.
I also tried all the suggestions mentioned above, but the issue still persists on my end.

**Comment by tomKFM** [comment]
@Jojocaster @muhammadhamza841 Can you test [this fix](https://github.com/doublesymmetry/react-native-track-player/pull/2517) ? 
It should solve the issue, let me know if it does not

**Comment by Jojocaster** [comment]
@tomKFM just gave it a go, it doesn't seem to fix the player on the lock screen 😕 The notification (in the media centre) works fine though.

**Comment by tomKFM** [comment]
@Jojocaster Unfortunately, i don't have this issue on my device (oneplus 13, android 15) :/ 

I cannot reproduce the bug, thus I cannot fix it.

Do you have any errors logs or it is simply not working at all without showing anything ?

**Comment by Jojocaster** [comment]
@tomKFM mine is a OnePlus9 stuck on Android 14, which is probably the issue. Ultimately that's not the end of the world as it seems to work fine on other Android devices. I'll try and share some logs later, the notification & the lock screen controls don't even show up anymore, they are displayed once on start and then disappear 😬
I'll try and get some logs in asap, thanks!

**Comment by Online13** [comment]
Hi. First of all, thank you for this library, it helps us a lot. 

In my case, I'm on Google Pixel 2xl, Android 11. Remote events don't work and registerPlaybackService is never called in my case. I tried calling playbackservice manually and setting remote listeners, but they don't work.  It's the same code I use with version 4.1.1 in production, but these features don't work for me in version 5.

**Comment by donaldchada** [comment]
on vs compactCapabilities: [Capability.Play, Capability.Pause], is not working and service.js its not being call and the status bar media controls are not responding

**Comment by j-q-in-berlin** [comment]
> [@zeevenn](https://github.com/zeevenn) try adding this to your local Kotlin in node_modules:
> 
> [#2507 (comment)](https://github.com/doublesymmetry/react-native-track-player/issues/2507#issuecomment-3263616306)

Thank you! This worked for me.

**Comment by muhammadhamza841** [comment]
@tomKFM thanks for the help — play, pause, forward, and backward are all working fine after the native changes.
However, the Jump Forward and Jump Backward buttons are still not working on Android 14 and lower.
They work perfectly on Android 15+

**Comment by decSunshineHe** [comment]
I reproduced the issue using the sample app on a physical device (Huawei nova 6 SE, HarmonyOS 3.0.0,similar to android 12?). In the lock screen notification, playback can be paused the first time, but subsequent clicks have no response, and the previous/next track buttons do not work either.

I’m still unsure whether the issue is caused by the Android version or the device manufacturer, since I tested several Android versions on the Android Studio emulator and didn’t encounter the same problem.

**Comment by decSunshineHe** [comment]
@jspizziri  First of all, thank you so much for your great contribution — it’s truly amazing! I created Android 10–16 virtual devices in Android Studio and found that on versions below or equal to Android 12, the playback control buttons (play, pause, previous, next) on the lock screen don’t work. The specific virtual devices tested were Pixel 3 XL Android 12.0 (“S”), Pixel 4a Android 11.0 (“R”), and Pixel 4 Android 10.0 (“Q”). All tests were conducted using the example project.

**Comment by bahmanworld** [comment]
I commented these lines in `MusicService.kt` for now till this issue be fixed.

1. With this approach, you just have `skip-prev`, `play/pause`, `skip-next` (It was the same then but they didn't work)
2. All default remote actions works fine 
3. `capabilities` and `notificationCapabilities` won't work where `updateOption` called.

##### Test
I tested these changes on real devices such as Galaxy A51(Android-13), Galaxy S25(Android-16) and works fine

##### At last not least 
I need `stop`, `like`, `dislike` on media notification

##### Let me know if this works for you:

<img width="804" height="727" alt="Image" src="https://github.com/user-attachments/assets/a6523ff6-5ef8-49e8-9db8-c0a9d8c6d8da" />

**Comment by lovegaoshi** [comment]
theres too much noise in this thread.

For the example app users - the way example app is [set up](https://github.com/doublesymmetry/react-native-track-player/blob/359af5a12d712d3b685530aed9b9625865a25d74/example/src/services/PlaybackService.ts#L6) is incorrect. if you only call TP.pause in RemotePlayPause its only going to pause. plain and simple. use your common sense. 

I'm still yet to see ANYONE did what I recommended - does[ onMediaButtonEvent ](https://github.com/doublesymmetry/react-native-track-player/blob/4f1e0c96b59cdab5dcf66d33a462a966b6bd4b7e/android/src/main/java/com/doublesymmetry/trackplayer/service/MusicService.kt#L946)fire? whats the intent? 

im quite astonished why double clicking in android studio to put a breakpoint online L946 in MusicService.kt is this hard for the average programmer.

**Comment by Jojocaster** [comment]
@lovegaoshi here's what I'm getting when trying to pause from the lockscreen: 
```
2025-11-21 17:47:42.027 19824-19824 RNTP-com.d...artCommand com.wonkylines.doyouworld.dev        D  onStartCommand: android.intent.action.MEDIA_BUTTON, null
```

I'm going to check whether `onMediaButtonEvent` gets called or not, I'll let keep you posted. 

**EDIT**: Nope, `onMediaButtonEvent` just doesn't get triggered even though the intent passed to `onStartCommand` is `android.intent.action.MEDIA_BUTTON`. Here's a full log of what I'm getting when taping the notification from the lock screen:

```
2025-11-21 18:06:16.789 24207-24207 RNTP-com.d...artCommand com.wonkylines.doyouworld.dev        D  onStartCommand: android.intent.action.MEDIA_BUTTON, null
2025-11-21 18:06:16.790  1556-16851 AudioFlingerExtImpl     audioserver                          D  AudioFlingerExtImpl oplusSetParameters: keyvalue onForegroundActivitiesChanged=com.wonkylines.doyouworld.dev:foreground:0
2025-11-21 18:06:16.795  1556-16851 AudioFlingerExtImpl     audioserver                          D  AudioFlingerExtImpl oplusSetParameters: keyvalue onForegroundActivitiesChanged=com.wonkylines.doyouworld.dev:foreground:1
2025-11-21 18:06:16.795  1556-16851 AudioFlingerExtImpl     audioserver                          D  updateForegroundInfo mForegroundMap(1)|[com.wonkylines.doyouworld.dev]=1
2025-11-21 18:06:18.159  5822-6185  Avrcp_ext               com.android.bluetooth                V  updateCurrentMediaState: mMediaController: MediaController (com.wonkylines.doyouworld.dev@7d9d3a5) (R) Sarahtonin And Royal Male, Do!!You!!!World, null
2025-11-21 18:06:18.570 24207-26029 BufferPoolAccessor2.0   com.wonkylines.doyouworld.dev        D  bufferpool2 0xb400007c92085028 : 5(40960 size) total buffers - 1(8192 size) used buffers - 1181/1186 (recycle/alloc) - 5/2369 (fetch/transfer)
2025-11-21 18:06:21.169  5822-6185  Avrcp_ext               com.android.bluetooth                V  updateCurrentMediaState: mMediaController: MediaController (com.wonkylines.doyouworld.dev@7d9d3a5) (R) Sarahtonin And Royal Male, Do!!You!!!World, null
```

**EDIT2**: Ok, another update. I've ejected my expo project, added breakpoints to the MusicService, and ran the app in debug mode. Interestingly, this fixed the lockscreen notification. I can see the `onMediaKeyEvent` being called with the right Intent. This is what I got using @tomKFM 's fix:

```
2025-11-22 10:34:00.088  5822-6185  Avrcp_ext               com.android.bluetooth                V  updateCurrentMediaState: mMediaController: MediaController (com.wonkylines.doyouworld@ec0245) (R) Dave Holloway 09/04/25, Do!!You!!!World, null
2025-11-22 10:34:00.862 28747-28747 RNTP-com.d...artCommand com.wonkylines.doyouworld            D  onStartCommand 1: android.intent.action.MEDIA_BUTTON, null
2025-11-22 10:34:00.862 28747-28747 RNTP-com.d...iaKeyEvent com.wonkylines.doyouworld            D  onMediaKeyEvent: android.intent.action.MEDIA_BUTTON, null
2025-11-22 10:34:00.864  1556-14345 AudioFlingerExtImpl     audioserver                          D  AudioFlingerExtImpl oplusSetParameters: keyvalue onForegroundActivitiesChanged=com.wonkylines.doyouworld:foreground:0
2025-11-22 10:34:00.865 28747-28836 ReactNativeJS           com.wonkylines.doyouworld            I  Event.RemotePlayPause
```

If I add this condition back, the notification stops working. It does look like Oxygen 14 has the same issue as Android 12, `onMediaButtonEvent` is never called.

```
         if (Build.VERSION.SDK_INT < Build.VERSION_CODES.TIRAMISU) {
            // HACK: this is not supposed to be here. I definitely screwed up. but Why?
            onMediaKeyEvent(intent)
         }
```

Hopefully this helps.

**Comment by lovegaoshi** [comment]
thanks for the input. So only some OEMs have this issue (wow android, great ecosystem!). Since this feature was developed with pixels and Samsungs and this is not the case in oneUI and native android, i dont see the path forward except monkey patching for each affected OEMs.

I'd recommend reaching out to the respective OEMs on why their android behaves like this. taking out the condition will most definitely double trigger onMediaKeyEvent for pixels and samsungs.

**Comment by Jojocaster** [comment]
@lovegaoshi no problem, I'll try and reach out to OnePlus but I doubt they'll patch Oxygen 14 just for us haha. 
It seems fine on Oxygen 15, so I might have to patch it for this version only. 
I'm thinking about adding this instead of the current condition: 

```
        val manufacturer = Build.MANUFACTURER
        val brand = Build.BRAND
        val isOnePlus = manufacturer.equals("OnePlus", ignoreCase = true) && brand.equals("OnePlus", ignoreCase = true);
        if (isOnePlus && Build.VERSION.SDK_INT < Build.VERSION_CODES.VANILLA_ICE_CREAM) {
            // HACK: this is not supposed to be here. I definitely screwed up. but Why?
            onMediaKeyEvent(intent)
         }
```

Any thoughts? Is this worth a PR?

**Comment by lovegaoshi** [comment]
i patch some features specifically for Samsung as well, so this approach is
100% valid and pr welcome. though testing solely relies on devs like you
who have oneplus phones. thank you!

**Comment by tomKFM** [comment]
@Jojocaster Yes I confirm, it seems to have been patch in OxygenOS 15 (Android 16)
And yes, I think it's worth a PR

**Comment by Jojocaster** [comment]
@tomKFM  @lovegaoshi  Cool, I'll test it properly and raise a PR asap.

**Comment by Jojocaster** [comment]
@lovegaoshi  Alright I'm back - sorry about the delay. I've got a fix ready to be submitted (it works just fine on Oxygen14 🎉 ), could you guys send me an invite so I can raise a PR?

**Comment by lovegaoshi** [comment]
tysm! i dont think u need any permissions to open a pr.

**Comment by Jojocaster** [comment]
@lovegaoshi  my bad, I was using the wrong remote 😄  Here's the PR: https://github.com/doublesymmetry/react-native-track-player/pull/2559
