### ISSUE TITLE
Context.startForegroundService() did not then call Service.startForeground()

### ISSUE THREAD

**Issue by xgustavoh** [DoubleSymmetry/react-native-track-player#524]
Good afternoon,
I had already commented on this error and had given it as "solved", but apparently the same still has problems.

Can it be "initialization" error of the component in React?

![screencapture-play-google-apps-publish-2019-04-02-14_08_09](https://user-images.githubusercontent.com/19254287/55578203-b7a72a80-56eb-11e9-805e-a6088691d72a.png)

Info `
Context.startForegroundService() did not then call Service.startForeground(), InvisibleToUser`:
![screencapture-play-google-apps-publish-2019-04-04-15_12_20](https://user-images.githubusercontent.com/19254287/55578424-41ef8e80-56ec-11e9-8988-3c563dd01137.png)

Info `Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{ba33f34 u0 com.hunterfm/com.guichaguri.trackplayer.service.MusicService}`:
![screencapture-play-google-apps-publish-2019-04-04-15_15_04](https://user-images.githubusercontent.com/19254287/55578537-91ce5580-56ec-11e9-9d1f-0409a960ced4.png)

**Comment by ishigamii** [comment]
Same here (https://github.com/react-native-kit/react-native-track-player/issues/473) 
I don't see anything in 1.1.4 that seems to solve this but I will give it a try just to check

**Comment by hiroyaiizuka** [comment]
any update ?

**Comment by FunkyLambda** [comment]
Not sure why there has been no update on this in over 6 months, but I'm having the same issue on v1.2.7.
They all appear to be happening on Android 11 devices according to my Crashlytics logs.

**Comment by reinhardholl** [comment]
We are seeing the same issue; Has anyone been able to solve it?

**Comment by mohity777** [comment]
Same happening in my app. 
![Screenshot 2021-06-29 at 3 51 01 PM](https://user-images.githubusercontent.com/56041802/123781410-d78d1f00-d8f1-11eb-97a5-5899c8e5cc84.png)

**Comment by justinhandley** [comment]
Also seeing this, so far on Pixel 3 and Samsung Galaxy 9 - all running Android 11

`Message

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{2a51d52 u0 org.monroeinstitute.expand/com.guichaguri.trackplayer.service.MusicService}

Traceback

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{2a51d52 u0 org.monroeinstitute.expand/com.guichaguri.trackplayer.service.MusicService}
  android.app.ActivityThread$H.handleMessage (ActivityThread.java:2005)
  android.os.Handler.dispatchMessage (Handler.java:106)
  android.os.Looper.loop (Looper.java:223)
  android.app.ActivityThread.main (ActivityThread.java:7664)
  java.lang.reflect.Method.invoke (Method.java:-2)
  com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:592)
  com.android.internal.os.ZygoteInit.main (ZygoteInit.java:947)`

**Comment by koreus7** [comment]
👍 Also seeing this. Only on Android 11 + Samsung.

**Comment by gyoung-panopto** [comment]
I'm seeing the same issue in crash logs as well. Android 11-only.

**Comment by sierrakn** [comment]
Has anyone found a workaround for this?

**Comment by mohity777** [comment]
Dead library.

**Comment by mohity777** [comment]
Why is it Closed?

**Comment by dcvz** [comment]
Thanks for flagging this again @mohity777 we're in the process of cleaning up the backlog to give us a better ability to fix issues and maintain this library. I'll reopen this issue as its still relevant!

**Comment by bradleyflood** [comment]
Should be resolved in ^v2.0.1

**Comment by mariasyedd** [comment]
Still occurring in v2.1.2

**Comment by jenshandersson** [comment]
This is still occurring in the latest 2.2.0-rc

`RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{392d34e u0 com.uptime/com.doublesymmetry.trackplayer.service.MusicService}`

**Comment by piotrekzawada** [comment]
still occurring in 2.1.3

`RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{607e5e9 u0 com.app.name/com.guichaguri.trackplayer.service.MusicService}`

**Comment by luancurti** [comment]
Still ocurring in `2.1.3` 

Tested devices with this problem

Device: `Samsung Galaxy S20 FE` OS Version: `Android 11`
Device: `Samsung Galaxy S20+` OS Version: `Android 12`

@doublesymmetry help us to fix this problem in this version before the breaking changes of the version `2.2.0`

**Comment by bplucas** [comment]
We still see this issue on `3.2.0` - It seems to be happening exclusively for Samsungs on Android 12 - Do you think we should reopen this issue?

**Comment by praisedavid787** [comment]
Hi guys, this issue needs to be reopened. It's been all over my play console as almost the only crash to be recorded multiple times a day. Only just started after 3.2.0 upgrade.

**Comment by martinmidtsund** [comment]
@praisedavid787 These are probably related https://github.com/doublesymmetry/react-native-track-player/issues/1676

**Comment by praisedavid787** [comment]
@martinmidtsund Definitely related sir, I'll follow up there.
