### ISSUE TITLE
[Android] Crash - android.app.RemoteServiceException

### ISSUE THREAD

**Issue by mojodev** [DoubleSymmetry/react-native-track-player#620]
i am getting crash logs on playstore for some of the devices:
```
android.app.RemoteServiceException: 
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1872)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:7045)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:965)
```
i tested on some of the devices it's working properly. i updated react native track player and target sdk version to 28. any idea why this crash happening ?

i am attaching Android versions and devices info on which crashes happens:

<img width="660" alt="Screen Shot 2019-06-08 at 8 21 09 PM" src="https://user-images.githubusercontent.com/16475786/59148873-d13a5a80-8a2b-11e9-881e-cad147f418af.png">

**Comment by roman-gula** [comment]
I have the same exception. Most of devices are Galaxies:

![image](https://user-images.githubusercontent.com/18235311/59609256-be0c4680-911f-11e9-8d93-c2ac893c4ea2.png)

**Comment by Guichaguri** [comment]
Can you share the code you're using on `updateOptions`?

**Comment by jasongrishkoff** [comment]
Hi @Guichaguri -- seeing this issue crop up for my users as well.  Here's what's being passed to `updateOptions`:
```
export const playerOptions = {
    maxArtworkSize: 500,
    capabilities: [
        TrackPlayer.CAPABILITY_PLAY,
        TrackPlayer.CAPABILITY_PAUSE,
        TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
        TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS,
        TrackPlayer.CAPABILITY_STOP,
    ],
    compactCapabilities: [
        TrackPlayer.CAPABILITY_PLAY,
        TrackPlayer.CAPABILITY_PAUSE,
        TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
        //TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS,
        TrackPlayer.CAPABILITY_STOP,
    ],
}
```

**Comment by roman-gula** [comment]
@Guichaguri My initial options:
``` 
await TrackPlayer.updateOptions({
    stopWithApp: true
});
```


Then I change capabilities when current track changes by calling `updateOptions`:
```
const updateOptions = async () => {
  const capabilities = getCapabilities();

  await TrackPlayer.updateOptions({
    capabilities
  });
};

const getCapabilities = () => {
  const result = [TrackPlayer.CAPABILITY_PLAY, TrackPlayer.CAPABILITY_PAUSE];

  const { prev, next } = store.getState().player.queueButtons;

  if (prev) {
    result.push(TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS);
  }

  if (next) {
    result.push(TrackPlayer.CAPABILITY_SKIP_TO_NEXT);
  }

  return result;
};
```

**Comment by hikkary** [comment]
Any updates on this ?

**Comment by ramazanarslan** [comment]
Any update ++?

**Comment by girish54321** [comment]
yes im all so having error any fix ?

**Comment by hiroyaiizuka** [comment]
any update?? still this error happens...

**Comment by neoassyrian** [comment]
I'm having similar issues. Any updates?

**Comment by taylorpringle** [comment]
I am also having this issue but can't seem to replicate it. Any fixes available?

**Comment by dungle27** [comment]
this issue still occur on latest version 1.2.3
please help us fix it.

**Comment by RayhanYulanda** [comment]
Same issue

**Comment by marioot** [comment]
Happens to us as well. Here are the options:

```  
await TrackPlayer.updateOptions({
    stopWithApp: true,
    capabilities: [
      TrackPlayer.CAPABILITY_PLAY,
      TrackPlayer.CAPABILITY_PAUSE,
      TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
      TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS,
      TrackPlayer.CAPABILITY_JUMP_FORWARD,
      TrackPlayer.CAPABILITY_JUMP_FORWARD,
      TrackPlayer.CAPABILITY_JUMP_BACKWARD,
    ],
    compactCapabilities: [
      TrackPlayer.CAPABILITY_PLAY,
      TrackPlayer.CAPABILITY_PAUSE,
      TrackPlayer.CAPABILITY_JUMP_FORWARD,
      TrackPlayer.CAPABILITY_JUMP_BACKWARD,
    ],
    notificationCapabilities: [
      TrackPlayer.CAPABILITY_PLAY,
      TrackPlayer.CAPABILITY_PAUSE,
      TrackPlayer.CAPABILITY_JUMP_FORWARD,
      TrackPlayer.CAPABILITY_JUMP_BACKWARD,
    ],
    jumpInterval: 15,
    icon: PLAYER_IMAGE,
    color: 0x157595,
  });
